version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  buildfront:
    working_directory: ~/Schola/frontend
    docker:
      - image: circleci/node:12.2
    steps:
      - checkout:
          path: ~/repo/frontend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  lintingfront:
    working_directory: ~/Schola/frontend
    docker:
      - image: circleci/node:12.2
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: npm run lint
  testfront:
    working_directory: ~/Schola/frontend
    docker:
      - image: circleci/node:12.2
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: npm run test
workflows:
  mergerequest:
    jobs:
      - buildfront
      - lintingfront:
          requires: [buildfront]
      - testfront:
          requires: [lintingfront]
